-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 16:07:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema easycondo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easycondo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easycondo` DEFAULT CHARACTER SET utf8 ;
USE `easycondo` ;

-- -----------------------------------------------------
-- Table `easycondo`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycondo`.`tb_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `documentNumber` VARCHAR(11) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `deviceToken` VARCHAR(255) NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME NOT NULL DEFAULT now(),
  `dtUpdated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documentNumber_UNIQUE` (`documentNumber` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycondo`.`tb_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycondo`.`tb_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permissionName` VARCHAR(30) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME NULL DEFAULT now(),
  `dtUpdated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycondo`.`tb_user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycondo`.`tb_user_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idPermission` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_user_permission_tb_user_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_tb_user_permission_tb_permissions1_idx` (`idPermission` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_permission_tb_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `easycondo`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_permission_tb_permissions1`
    FOREIGN KEY (`idPermission`)
    REFERENCES `easycondo`.`tb_permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycondo`.`tb_condo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycondo`.`tb_condo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `condoName` VARCHAR(100) NOT NULL,
  `documentCNPJ` VARCHAR(14) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `imageUrl` VARCHAR(255) NULL,
  `zipcode` VARCHAR(8) NOT NULL,
  `addressNumber` INT NOT NULL,
  `addressOptional` VARCHAR(100) NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME NOT NULL DEFAULT now(),
  `dtUpdated` DATETIME NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documentCNPJ_UNIQUE` (`documentCNPJ` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `addressNumber_UNIQUE` (`addressNumber` ASC) VISIBLE,
  INDEX `fk_tb_condo_tb_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_tb_condo_tb_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `easycondo`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycondo`.`tb_residents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycondo`.`tb_residents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` INT NOT NULL,
  `roomOptional` VARCHAR(5) NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME NOT NULL DEFAULT now(),
  `dtUpdated` DATETIME NULL,
  `idCondo` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_residents_tb_condo1_idx` (`idCondo` ASC) VISIBLE,
  INDEX `fk_tb_residents_tb_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_tb_residents_tb_condo1`
    FOREIGN KEY (`idCondo`)
    REFERENCES `easycondo`.`tb_condo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_residents_tb_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `easycondo`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycondo`.`tb_notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycondo`.`tb_notice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `subtitle` VARCHAR(100) NOT NULL,
  `archiveTitle` VARCHAR(45) NOT NULL,
  `archiveType` VARCHAR(45) NOT NULL,
  `archiveSize` VARCHAR(10) NOT NULL,
  `archive` MEDIUMBLOB NOT NULL,
  `dtUploaded` DATETIME NOT NULL DEFAULT now(),
  `idCondo` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_notice_tb_condo1_idx` (`idCondo` ASC) VISIBLE,
  INDEX `fk_tb_notice_tb_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_tb_notice_tb_condo1`
    FOREIGN KEY (`idCondo`)
    REFERENCES `easycondo`.`tb_condo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_notice_tb_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `easycondo`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycondo`.`tb_push`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycondo`.`tb_push` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `dtSent` DATETIME NOT NULL DEFAULT now(),
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_push_tb_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_tb_push_tb_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `easycondo`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
