
version: '3.4'
services:
  db:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'easycondo'   
      MYSQL_USER: 'dart_user'
      MYSQL_PASSWORD: 'dart_pass'      
      MYSQL_ROOT_PASSWORD: root
    platform: linux/arm64
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - "./database.sql:/docker-entrypoint-initdb.d/1.sql"
